In [2]:
import ctypes
import numpy as np

In [ ]:
lib = ctypes.CDLL('./compute_B_matrix.so')

lib.compute_B_matrix.argtypes = [
    ctypes.POINTER(ctypes.c_double),  # B (output)
    ctypes.POINTER(ctypes.c_double),  # tx
    ctypes.POINTER(ctypes.c_double),  # ty
    ctypes.POINTER(ctypes.c_double),  # tz
    ctypes.c_int,                     # horizon
    ctypes.c_double,                  # Ix
    ctypes.c_double,                  # Iy
    ctypes.c_double,                  # Iz
    ctypes.c_double,                  # m
    ctypes.c_double                   # dt
]
lib.compute_B_matrix_sing.argtypes = [
    ctypes.POINTER(ctypes.c_double),  # B (output)
    ctypes.c_double,  # tx
    ctypes.c_double,  # ty
    ctypes.c_double,  # tz
    ctypes.c_int,                     # horizon
    ctypes.c_double,                  # Ix
    ctypes.c_double,                  # Iy
    ctypes.c_double,                  # Iz
    ctypes.c_double,                  # m
    ctypes.c_double                   # dt
]
lib.compute_next_state.argtypes = [
    ctypes.POINTER(ctypes.c_double),  # x_next
    ctypes.POINTER(ctypes.c_double),  # px
    ctypes.POINTER(ctypes.c_double),  # py
    ctypes.POINTER(ctypes.c_double),  # pz
    ctypes.POINTER(ctypes.c_double),  # pdotx
    ctypes.POINTER(ctypes.c_double),  # pdoty
    ctypes.POINTER(ctypes.c_double),  # pdotz
    ctypes.POINTER(ctypes.c_double),  # tx
    ctypes.POINTER(ctypes.c_double),  # ty
    ctypes.POINTER(ctypes.c_double),  # tz
    ctypes.POINTER(ctypes.c_double),  # tdotx
    ctypes.POINTER(ctypes.c_double),  # tdoty
    ctypes.POINTER(ctypes.c_double),  # tdotz
    ctypes.POINTER(ctypes.c_double),  # Tau
    ctypes.POINTER(ctypes.c_double),  # taux
    ctypes.POINTER(ctypes.c_double),  # tauy
    ctypes.POINTER(ctypes.c_double),  # tauz
    ctypes.c_int,                     # horizon
    ctypes.c_double,                  # Ix
    ctypes.c_double,                  # Iy
    ctypes.c_double,                  # Iz
    ctypes.c_double,                  # kd
    ctypes.c_double,                  # m
    ctypes.c_double                   # dt
]

In [11]:
x = np.random.rand(12).reshape(12, -1)
u = np.random.rand(4)
horizon = 1
Ix, Iy, Iz = 1.0, 1.0, 1.0
m, dt = 1.0, 0.01
tx, ty, tz = x[6], x[7], x[8]
# 创建输出数组
B = np.zeros((12, 4, horizon), dtype=np.float64)

# 调用C++函数
lib.compute_B_matrix(
    B.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tx.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    ty.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    horizon, Ix, Iy, Iz, m, dt
)
print(B[:,:,0])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.74935257e-03  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.44225500e-03  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 9.29927153e-03  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e-04  2.15113673e-05  3.31828705e-05]
 [ 0.00000000e+00  0.00000000e+00  8.39107380e-05 -5.43965812e-05]
 [ 0.00000000e+00  0.00000000e+00  5.84955295e-05  9.02336680e-05]
 [ 0.00000000e+00  1.00000000e-02  2.15113673e-03  3.31828705e-03]
 [ 0.00000000e+00  0.00000000e+00  8.39107380e-03 -5.43965812e-03]
 [ 0.00000000e+00  0.00000000e+00  5.84955295e-03  9.02336680e-03]]


In [4]:
import numpy as np
import ctypes
libd = ctypes.CDLL('./compute_dynamics.so')

libd.compute_A_matrix.argtypes = [
    ctypes.POINTER(ctypes.c_double),  # A (output)
    ctypes.POINTER(ctypes.c_double),  # tx
    ctypes.POINTER(ctypes.c_double),  # ty
    ctypes.POINTER(ctypes.c_double),  # tz
    ctypes.POINTER(ctypes.c_double),  # tdotx
    ctypes.POINTER(ctypes.c_double),  # tdoty
    ctypes.POINTER(ctypes.c_double),  # tdotz
    ctypes.POINTER(ctypes.c_double),  # Tau
    ctypes.POINTER(ctypes.c_double),  # taux
    ctypes.POINTER(ctypes.c_double),  # tauy
    ctypes.POINTER(ctypes.c_double),  # tauz
    ctypes.c_int,                     # horizon
    ctypes.c_double,                  # Ix
    ctypes.c_double,                  # Iy
    ctypes.c_double,                  # Iz
    ctypes.c_double,                  # kd
    ctypes.c_double,                  # m
    ctypes.c_double                   # dt
]
libd.compute_next_state.argtypes = [
    ctypes.POINTER(ctypes.c_double),  # x_next
    ctypes.POINTER(ctypes.c_double),  # px
    ctypes.POINTER(ctypes.c_double),  # py
    ctypes.POINTER(ctypes.c_double),  # pz
    ctypes.POINTER(ctypes.c_double),  # pdotx
    ctypes.POINTER(ctypes.c_double),  # pdoty
    ctypes.POINTER(ctypes.c_double),  # pdotz
    ctypes.POINTER(ctypes.c_double),  # tx
    ctypes.POINTER(ctypes.c_double),  # ty
    ctypes.POINTER(ctypes.c_double),  # tz
    ctypes.POINTER(ctypes.c_double),  # tdotx
    ctypes.POINTER(ctypes.c_double),  # tdoty
    ctypes.POINTER(ctypes.c_double),  # tdotz
    ctypes.POINTER(ctypes.c_double),  # Tau
    ctypes.POINTER(ctypes.c_double),  # taux
    ctypes.POINTER(ctypes.c_double),  # tauy
    ctypes.POINTER(ctypes.c_double),  # tauz
    ctypes.c_int,                     # horizon
    ctypes.c_double,                  # Ix
    ctypes.c_double,                  # Iy
    ctypes.c_double,                  # Iz
    ctypes.c_double,                  # kd
    ctypes.c_double,                  # m
    ctypes.c_double                   # dt
]

In [8]:
x = np.random.rand(12).reshape(12, -1)
u = np.random.rand(4).reshape(4, -1)
xnext = np.zeros_like(x)
horizon = 1
Ix, Iy, Iz = 1.0, 1.0, 1.0
m, kd, dt = 1.0, 0.01, 0.1
Tau, taux, tauy, tauz = u[0], u[1], u[2], u[3]
tx, ty, tz = x[6], x[7], x[8]
tdotx, tdoty, tdotz = x[9], x[10], x[11]
# 创建输出数组
A = np.zeros((12, 12, horizon), dtype=np.float64)

libd.compute_A_matrix(
    A.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tx.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    ty.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tdotx.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tdoty.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tdotz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    Tau.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    taux.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tauy.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tauz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    horizon, Ix, Iy, Iz, kd, m, dt
)

0

In [9]:
px, py, pz = x[0], x[1], x[2]
pdotx, pdoty, pdotz = x[3], x[4], x[5]
tx, ty, tz = x[6], x[7], x[8]
tdotx, tdoty, tdotz = x[9], x[10], x[11]
Tau, taux, tauy, tauz = u[0], u[1], u[2], u[3]
libd.compute_next_state(
    xnext.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    px.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    py.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    pz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    pdotx.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    pdoty.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    pdotz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tx.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    ty.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tdotx.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tdoty.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tdotz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    Tau.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    taux.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tauy.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    tauz.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
    1, Ix, Iy, Iz, kd, m, dt
)

0